format:
  revealjs:
    theme: [custom.scss]
editor: visual
title-slide-attributes: 
  data-background-color: "#212121"
project:
  type: website
  output-dir: docs
macros: _macros.tex # import a list of TeX/LaTeX definitions